import type { LessonPlan, UserStats } from './types';

export const INITIAL_USER_STATS: UserStats = {
  name: 'Alex Rivera',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  currentLevelBadge: 'Adaptive Scholar',
  overallMastery: 78,
  completedLessonsCount: 14,
  studyStreakDays: 6,
  totalStudyHours: 24.5,
  strongConcepts: [
    { concept: 'Qubit Superposition', masteryScore: 92, status: 'Strong', category: 'Physics / AI', lastPracticed: '2 days ago' },
    { concept: 'Backpropagation Algorithm', masteryScore: 88, status: 'Strong', category: 'Machine Learning', lastPracticed: 'Yesterday' },
    { concept: 'REST vs GraphQL API', masteryScore: 95, status: 'Strong', category: 'Software Architecture', lastPracticed: '3 days ago' },
    { concept: 'Light Reaction in Chloroplasts', masteryScore: 84, status: 'Strong', category: 'Biology', lastPracticed: '5 days ago' },
  ],
  weakConcepts: [
    { concept: 'Quantum Entanglement & Teleportation', masteryScore: 48, status: 'Weak', category: 'Physics / AI', lastPracticed: 'Yesterday' },
    { concept: 'Vanishing Gradient Problem', masteryScore: 54, status: 'Weak', category: 'Machine Learning', lastPracticed: '4 days ago' },
    { concept: 'Calvin Cycle Dark Reactions', masteryScore: 58, status: 'Weak', category: 'Biology', lastPracticed: '6 days ago' },
    { concept: 'Consensus Algorithms (Raft & Paxos)', masteryScore: 61, status: 'Developing', category: 'System Design', lastPracticed: '1 week ago' },
  ],
  recentScores: [
    { id: 'score-1', lessonTitle: 'Quantum Superposition & Qubits', date: 'Yesterday', score: 85, totalQuestions: 5, correctCount: 4, timeSpentMinutes: 20 },
    { id: 'score-2', lessonTitle: 'Deep Neural Networks 101', date: '3 days ago', score: 90, totalQuestions: 6, correctCount: 5, timeSpentMinutes: 30 },
    { id: 'score-3', lessonTitle: 'Microservices & Distributed Caching', date: '5 days ago', score: 75, totalQuestions: 4, correctCount: 3, timeSpentMinutes: 15 },
  ],
  weeklyActivity: [
    { day: 'Mon', hours: 2.5, score: 82 },
    { day: 'Tue', hours: 4.0, score: 88 },
    { day: 'Wed', hours: 1.5, score: 76 },
    { day: 'Thu', hours: 3.5, score: 90 },
    { day: 'Fri', hours: 5.0, score: 85 },
    { day: 'Sat', hours: 6.2, score: 94 },
    { day: 'Sun', hours: 1.8, score: 80 },
  ],
};

export const SAMPLE_LESSONS: Record<string, LessonPlan> = {
  quantum: {
    id: 'quantum-computing-101',
    topicTitle: 'Quantum Computing & Qubit Mechanics',
    level: 'Intermediate',
    language: 'English',
    duration: 20,
    goal: 'Concept Mastery',
    sourceType: 'topic',
    sourceName: 'Quantum Computing Fundamentals.pdf',
    createdAt: '2026-09-03',
    modules: [
      {
        id: 'mod-1',
        title: 'Module 1: Classical Bits vs Quantum Qubits',
        description: 'Understand how superposition allows a qubit to hold 0 and 1 simultaneously.',
        conceptsCovered: ['Binary Bits', 'Qubit States |0⟩ and |1⟩', 'Superposition Principle'],
        realWorldExample: 'Flipping a coin: in mid-air, it is both heads and tails at once until observed.',
        estimatedMinutes: 5,
      },
      {
        id: 'mod-2',
        title: 'Module 2: Quantum Entanglement & Teleportation',
        description: 'Discover spooky action at a distance and paired qubit synchronization.',
        conceptsCovered: ['Entangled Pairs', 'Bell States', 'Quantum Teleportation'],
        realWorldExample: 'A pair of magical dice where rolling an even number on one instantly forces the second dice to be even across the galaxy.',
        estimatedMinutes: 8,
      },
      {
        id: 'mod-3',
        title: 'Module 3: Quantum Gates & Real-World Algorithms',
        description: 'Explore Hadamard gates and Grover / Shor algorithms for exponential speedup.',
        conceptsCovered: ['Hadamard Gate (H)', 'CNOT Gate', 'Quantum Encryption Speedup'],
        realWorldExample: 'Searching an unsorted database of 1 billion items in 31,622 steps instead of 500 million steps.',
        estimatedMinutes: 7,
      },
    ],
    slides: [
      {
        id: 1,
        title: '1. Fundamentals: Classical Bits vs Qubits',
        narrationText: "Welcome to AdaptiveAI Teacher! Today we are exploring Quantum Computing. While classical computers rely on binary bits that are either strictly 0 or strictly 1, a quantum computer uses Qubits. Qubits can exist in a state called Superposition, representing both 0 and 1 at the same time!",
        narrationTextTranslations: {
          English: "Welcome to AdaptiveAI Teacher! Today we are exploring Quantum Computing. While classical computers rely on binary bits that are either strictly 0 or strictly 1, a quantum computer uses Qubits. Qubits can exist in a state called Superposition, representing both 0 and 1 at the same time!",
          Hindi: "AdaptiveAI Teacher में आपका स्वागत है! आज हम क्वांटम कंप्यूटिंग की खोज कर रहे हैं। शास्त्रीय कंप्यूटर 0 या 1 बिट्स का उपयोग करते हैं, लेकिन क्वांटम कंप्यूटर Qubits का उपयोग करते हैं जो एक साथ 0 और 1 दोनों हो सकते हैं!",
          Hinglish: "AdaptiveAI Teacher me aapka swagat hai! Aaj hum Quantum Computing seekhenge. Classical computers bit 0 ya 1 use karte hain, lekin Qubit ek sath 0 aur 1 dono ho sakta hai superposition ke dwara!",
          Marathi: "AdaptiveAI Teacher मध्ये आपले स्वागत आहे! आज आपण क्वांटम कॉम्प्युटिंग शिकत आहोत. क्लासिकल संगणक 0 किंवा 1 वापरतात, परंतु क्वांटम कॉम्प्युटर Qubits वापरतात जे एकाच वेळी 0 आणि 1 असू शकतात!",
        },
        visualType: 'comparison',
        visualContent: {
          subtitle: 'State Space Comparison',
          items: [
            'Classical Bit: Dual States Only [0] or [1]',
            'Quantum Qubit: Superposition α|0⟩ + β|1⟩',
            'Bloch Sphere representation allows infinite probability vectors',
            'Exponential scaling: N qubits hold 2^N parallel states!',
          ],
          analogyText: 'Analogy: A spinning coin in mid-air is simultaneously Heads and Tails until caught.',
        },
      },
      {
        id: 2,
        title: '2. Superposition & Bloch Sphere',
        narrationText: "Let's inspect the Bloch Sphere! The top pole represents state |0⟩ and the bottom pole represents state |1⟩. Any point on the surface of the sphere represents a valid quantum superposition with state amplitudes alpha and beta.",
        narrationTextTranslations: {
          English: "Let's inspect the Bloch Sphere! The top pole represents state |0⟩ and the bottom pole represents state |1⟩. Any point on the surface of the sphere represents a valid quantum superposition with state amplitudes alpha and beta.",
          Hindi: "ब्लोच क्षेत्र को देखें! ऊपर का ध्रुव |0⟩ स्थिति का प्रतिनिधित्व करता है और निचला ध्रुव |1⟩ स्थिति का। सतह पर कोई भी बिंदु एक सुपरपोजिशन है।",
          Hinglish: "Bloch Sphere ko dekhiye! Top pole |0⟩ hai aur bottom pole |1⟩ hai. Surface par koi bhi point ek valid quantum superposition status hai.",
          Marathi: "ब्लॉच स्फेअर पहा! वरील ध्रुव |0⟩ आणि खालील ध्रुव |1⟩ दर्शवतो. पृष्ठभागावरील कोणताही बिंदू सुपरपोझिशन दर्शवतो.",
        },
        visualType: 'formula',
        visualContent: {
          subtitle: 'State Vector Formula',
          formula: '|Ψ⟩ = cos(θ/2)|0⟩ + e^(iφ)sin(θ/2)|1⟩',
          items: [
            '|α|^2 + |β|^2 = 1 (Total Probability Rule)',
            'Hadamard Gate (H) transforms |0⟩ -> 1/√2 (|0⟩ + |1⟩)',
            'Measurement forces wave function collapse to discrete 0 or 1',
          ],
        },
        hasCheckpoint: true,
        checkpoint: {
          id: 'cp-1',
          question: 'If a Qubit is placed into a 50/50 Superposition using a Hadamard gate, what is the probability of measuring state |0⟩?',
          options: ['0% (It is locked to 1)', '50% (Equal probability)', '100% (It always stays |0⟩)', '25% (Quarter probability)'],
          correctAnswer: 1,
          explanation: 'Superposition created by Hadamard gate grants equal probability amplitudes (|α|^2 = 0.5), yielding a 50% chance of measuring 0.',
          adaptiveRemediation: {
            simplifiedNarration: "No worries! Let's adapt and simplify this. Imagine a fair coin flip. Before you catch it, it is 50% heads and 50% tails. The Hadamard gate sets up that exact fair 50/50 probability spin!",
            simplifiedVisual: "Analogy visual: Fair Coin Flip -> 50% Heads (|0⟩) / 50% Tails (|1⟩). |α|^2 = 0.5, |β|^2 = 0.5.",
            followUpQuestion: 'If you flip a fair quantum coin, how often will it land on state |0⟩ across 100 trials?',
            followUpOptions: ['Around 50 times', 'Exactly 0 times', 'Exactly 100 times', '25 times'],
            followUpCorrectAnswer: 0,
          },
        },
      },
      {
        id: 3,
        title: '3. Quantum Entanglement & Real-World Applications',
        narrationText: "Now let's explore Quantum Entanglement! When two qubits become entangled, measuring Qubit A instantaneously determines the state of Qubit B, regardless of lightyears separating them. This enables quantum cryptography and unbreakable quantum networks.",
        narrationTextTranslations: {
          English: "Now let's explore Quantum Entanglement! When two qubits become entangled, measuring Qubit A instantaneously determines the state of Qubit B, regardless of lightyears separating them. This enables quantum cryptography and unbreakable quantum networks.",
          Hindi: "अब हम क्वांटम एंटैंगलमेंट का अध्ययन करेंगे! जब दो qubits उलझ जाते हैं, तो एक मापने पर दूसरे का उत्तर तुरंत पता चलता है।",
          Hinglish: "Ab hum Quantum Entanglement dekhenge! Jab do qubits entangle hote hain, ek ko measure karte hi doosre ka state instant pata chal jata hai.",
          Marathi: "आता आपण क्वांटम एंटँगलमेंट पाहूया! जेव्हा दोन Qubits एंटँगल होतात, तेव्हा एकाची मोजणी करताच दुसऱ्याची स्थिती लगेच निश्चित होते.",
        },
        visualType: 'flowchart',
        visualContent: {
          subtitle: 'Quantum Teleportation & Cryptography Pipeline',
          diagramSteps: [
            { title: 'Step 1: Entangle', desc: 'Create Bell Pair |Φ+⟩ using Hadamard & CNOT gates', icon: 'Sparkles' },
            { title: 'Step 2: Separate', desc: 'Distribute Qubit A to Alice and Qubit B to Bob', icon: 'Network' },
            { title: 'Step 3: Measure', desc: 'Alice measures her qubit -> Bob state collapses instantly', icon: 'Zap' },
            { title: 'Step 4: Decode', desc: 'Send 2 classical bits to unlock teleported state', icon: 'ShieldCheck' },
          ],
        },
      },
    ],
    assessmentQuestions: [
      {
        id: 'q1',
        type: 'mcq',
        question: 'What principle allows a Qubit to process multiple computational paths simultaneously?',
        options: ['Quantum Superposition', 'Binary Encoding', 'Thermal Dissipation', 'Classical Logic Gating'],
        correctAnswer: 0,
        conceptTested: 'Qubit Superposition',
        explanation: 'Superposition enables qubits to exist as linear combinations of states, processing parallel vectors simultaneously.',
      },
      {
        id: 'q2',
        type: 'mcq',
        question: 'Which quantum gate is primarily used to put a qubit into a superposition state?',
        options: ['Pauli-X Gate', 'Hadamard Gate (H)', 'SWAP Gate', 'AND Gate'],
        correctAnswer: 1,
        conceptTested: 'Quantum Gates',
        explanation: 'The Hadamard gate maps basis states |0⟩ and |1⟩ into equal superposition states.',
      },
      {
        id: 'q3',
        type: 'mcq',
        question: 'What occurs when a qubit in superposition is measured by an observer?',
        options: [
          'The wave function expands indefinitely',
          'The qubit collapses to a single definite state (0 or 1)',
          'The qubit duplicates into two identical particles',
          'Nothing changes; superposition remains',
        ],
        correctAnswer: 1,
        conceptTested: 'Measurement Collapse',
        explanation: 'Measurement causes wave-function collapse, turning probabilistic states into a deterministic output.',
      },
      {
        id: 'q4',
        type: 'mcq',
        question: 'How does N qubits compare to N classical bits in storage capacity?',
        options: ['N qubits hold N bits', 'N qubits hold N^2 states', 'N qubits hold 2^N states simultaneously', 'N qubits hold 1 bit'],
        correctAnswer: 2,
        conceptTested: 'Quantum Scaling',
        explanation: 'Quantum registers scale exponentially (2^N coefficients), providing immense computing power.',
      },
    ],
  },
  ai: {
    id: 'deep-learning-101',
    topicTitle: 'Neural Networks & Deep Learning',
    level: 'Beginner',
    language: 'English',
    duration: 15,
    goal: 'Concept Mastery',
    sourceType: 'topic',
    sourceName: 'Machine Learning Masterclass.pptx',
    createdAt: '2026-09-02',
    modules: [
      {
        id: 'm1',
        title: 'Module 1: The Artificial Neuron (Perceptron)',
        description: 'How inputs, weights, biases, and activation functions work.',
        conceptsCovered: ['Inputs & Weights', 'Bias Term', 'ReLU & Sigmoid Activations'],
        realWorldExample: 'Calculating if you should go to a concert based on ticket price, weather, and friends going.',
        estimatedMinutes: 5,
      },
      {
        id: 'm2',
        title: 'Module 2: Forward Pass & Loss Functions',
        description: 'Tracing signals from input layer to output prediction.',
        conceptsCovered: ['Forward Propagation', 'Mean Squared Error', 'Cross-Entropy Loss'],
        realWorldExample: 'A student taking a practice test and grading how far off their answers are from 100%.',
        estimatedMinutes: 5,
      },
      {
        id: 'm3',
        title: 'Module 3: Backpropagation & Gradient Descent',
        description: 'Updating weights backward using calculus gradient steps.',
        conceptsCovered: ['Gradient Descent', 'Learning Rate', 'Weight Tuning'],
        realWorldExample: 'Walking down a foggy mountain by feeling which slope steps downward.',
        estimatedMinutes: 5,
      },
    ],
    slides: [
      {
        id: 1,
        title: '1. The Artificial Neuron (Perceptron)',
        narrationText: "Welcome! Today we step inside Artificial Neural Networks. At the heart of AI is the Artificial Neuron. It takes numeric inputs, multiplies them by weights, adds a bias value, and passes the sum through an activation function like ReLU to trigger output!",
        narrationTextTranslations: {
          English: "Welcome! Today we step inside Artificial Neural Networks. At the heart of AI is the Artificial Neuron. It takes numeric inputs, multiplies them by weights, adds a bias value, and passes the sum through an activation function like ReLU to trigger output!",
          Hindi: "आपका स्वागत है! आज हम आर्टिफिशियल न्यूरल नेटवर्क का अध्ययन करेंगे। AI के केंद्र में आर्टिफिशियल न्यूरॉन है। यह इनपुट लेता है, भार से गुणा करता है, और ReLU फंक्शन चलाता है!",
          Hinglish: "Welcome! Aaj hum Neural Networks seekhenge. Perceptron me inputs weights se multiply hote hain, bias add hota hai aur ReLU activation trigger hota hai!",
          Marathi: "स्वागत आहे! आज आपण न्यूरल नेटवर्क शिकूया. कृत्रिम न्यूरॉन इनपुट्स घेतो, वजनाने गुणतो आणि आउटपुट तयार करतो!",
        },
        visualType: 'diagram',
        visualContent: {
          subtitle: 'Perceptron Mathematical Model',
          codeSnippet: `Inputs: [x1, x2, x3]\nWeights: [w1, w2, w3]\nZ = (x1*w1 + x2*w2 + x3*w3) + Bias\nOutput = ReLU(Z) = max(0, Z)`,
          items: [
            'Weights determine importance of each input feature',
            'Bias shifts the activation threshold up or down',
            'Activation functions introduce non-linearity so networks learn complex patterns',
          ],
        },
      },
      {
        id: 2,
        title: '2. Backpropagation & Weight Tuning',
        narrationText: "How does AI actually learn? Through Backpropagation! The network compares its prediction to the correct answer to calculate Loss. Then it computes gradients backward using chain rule to adjust weights slightly in the direction that lowers error.",
        narrationTextTranslations: {
          English: "How does AI actually learn? Through Backpropagation! The network compares its prediction to the correct answer to calculate Loss. Then it computes gradients backward using chain rule to adjust weights slightly in the direction that lowers error.",
          Hindi: "AI कैसे सीखता है? बैकप्रोपेगेशन द्वारा! नेटवर्क अपनी भविष्यवाणी की तुलना सही उत्तर से करता है और नुकसान को कम करने के लिए भार को अपडेट करता है।",
          Hinglish: "AI kaise seekhta hai? Backpropagation se! Prediction ko target se compare karke loss calculate hota hai aur weights update hote hain.",
          Marathi: "AI कसे शिकते? बॅकप्रॉपॅगेशनद्वारे! त्रुटी कमी करण्यासाठी न्यूरल नेटवर्क वजनांचे समायोजन करते.",
        },
        visualType: 'formula',
        visualContent: {
          subtitle: 'Gradient Descent Weight Update Rule',
          formula: 'w_new = w_old - η * (∂Loss / ∂w)',
          items: [
            'η (eta) is the Learning Rate parameter',
            'Too high learning rate = overshoot minimum error',
            'Too low learning rate = extremely slow training',
          ],
        },
        hasCheckpoint: true,
        checkpoint: {
          id: 'cp-2',
          question: 'If the learning rate (η) is set to an excessively high value (e.g., η = 10.0), what is likely to happen during gradient descent?',
          options: [
            'The network converges to perfection instantly',
            'The model overshoots the minimum and loss diverges',
            'The training speed drops to zero',
            'No weights will ever change',
          ],
          correctAnswer: 1,
          explanation: 'An overly large learning rate causes step sizes to overshoot the global loss minimum, causing oscillating or diverging loss values.',
          adaptiveRemediation: {
            simplifiedNarration: "Let's adapt the view! Think of taking giant 10-foot leaps down a small staircase. You will jump right over the landing spot and crash into the opposite wall! That's why learning rate needs small, controlled steps.",
            simplifiedVisual: "Analogy Visual: Small Steps vs Giant Leaps. High Learning Rate = Overshooting the valley bottom.",
            followUpQuestion: 'To reach the very bottom of a valley safely, should your steps be huge leaps or controlled small steps?',
            followUpOptions: ['Controlled small steps', 'Huge blind leaps', 'Zero steps', 'Backwards leaps'],
            followUpCorrectAnswer: 0,
          },
        },
      },
    ],
    assessmentQuestions: [
      {
        id: 'aq-1',
        type: 'mcq',
        question: 'What is the role of an Activation Function (like ReLU) in a neural network?',
        options: ['To add non-linearity', 'To clear RAM memory', 'To encrypt data', 'To convert text to audio'],
        correctAnswer: 0,
        conceptTested: 'Activation Functions',
        explanation: 'Activation functions allow neural networks to model non-linear, complex boundary functions.',
      },
      {
        id: 'aq-2',
        type: 'mcq',
        question: 'Which algorithm is used to calculate partial derivatives of loss with respect to weights?',
        options: ['Backpropagation', 'Dijkstra Algorithm', 'Bubble Sort', 'K-Means Clustering'],
        correctAnswer: 0,
        conceptTested: 'Backpropagation Algorithm',
        explanation: 'Backpropagation uses calculus chain rule to compute gradients backward layer by layer.',
      },
    ],
  },
};
